import { describe, expect, it } from 'vitest'
import { BfskDetector } from '../../src/domain/bfskDetector'
import { defaultBfskConfiguration, defaultBfskDetectorThresholds } from '../../src/domain/bfskConfiguration'
import { BfskModulator } from '../../src/domain/bfsk'

const sampleRate = 48000
const modulator = new BfskModulator(defaultBfskConfiguration)
const detector = new BfskDetector(defaultBfskConfiguration, defaultBfskDetectorThresholds)

/**
 * addModerateNoise adds deterministic low-amplitude noise to a modulated PCM signal.
 * @param {Float32Array} samples - Source samples generated by the existing BFSK modulator.
 * @returns {Float32Array} Noisy PCM samples for detector resilience testing.
 */
function addModerateNoise(samples: Float32Array): Float32Array {
  return Float32Array.from(samples, (sample, index) => sample * 0.75 + ((((index * 17) % 29) - 14) / 14) * 0.03)
}

describe('BfskDetector', () => {
  it('detects zero from PCM generated by the existing BFSK modulator', () => {
    const result = detector.detect(modulator.modulate([0], sampleRate), sampleRate)

    expect(result.symbol).toBe(0)
    expect(result.zeroEnergy).toBeGreaterThan(result.oneEnergy)
    expect(result.confidence).toBeGreaterThan(defaultBfskDetectorThresholds.minimumConfidence)
  })

  it('detects one from PCM generated by the existing BFSK modulator', () => {
    const result = detector.detect(modulator.modulate([1], sampleRate), sampleRate)

    expect(result.symbol).toBe(1)
    expect(result.oneEnergy).toBeGreaterThan(result.zeroEnergy)
    expect(result.confidence).toBeGreaterThan(defaultBfskDetectorThresholds.minimumConfidence)
  })

  it('returns none for silence', () => {
    expect(detector.detect(new Float32Array(480), sampleRate).symbol).toBe('none')
  })

  it('detects a modulated one with moderate amplitude variation and noise', () => {
    const noisySamples = addModerateNoise(modulator.modulate([1], sampleRate))

    expect(detector.detect(noisySamples, sampleRate).symbol).toBe(1)
  })
})
