import { describe, expect, it } from 'vitest'
import type { AudioOutput, AudioPlayback } from '../../src/adapters/audio/webAudioPcmPlayer'
import { DiagnosticToneService } from '../../src/application/diagnosticTone'
import { BfskModulator } from '../../src/domain/bfsk'
import { defaultBfskConfiguration } from '../../src/domain/bfskConfiguration'

class TestAudioOutput implements AudioOutput {
  readonly sampleRate = 8000
  readonly playback: AudioPlayback = { completed: new Promise<void>(() => undefined), stop: () => { this.stopped = true } }
  stopped = false
  disposed = false
  receivedSamples: Float32Array | undefined

  /**
   * play records production-modulated samples for diagnostic orchestration tests.
   * @param {Float32Array} samples - PCM samples generated by the shared BFSK modulator.
   * @returns {Promise<AudioPlayback>} Controllable test playback handle.
   */
  async play(samples: Float32Array): Promise<AudioPlayback> {
    this.receivedSamples = samples
    return this.playback
  }

  /**
   * dispose marks the test output as released.
   * @returns {Promise<void>} Completed cleanup promise.
   */
  async dispose(): Promise<void> {
    this.disposed = true
  }
}

describe('DiagnosticToneService', () => {
  it('uses the shared modulator to start a long zero tone and releases it on stop', async () => {
    const output = new TestAudioOutput()
    const service = new DiagnosticToneService(new BfskModulator(defaultBfskConfiguration), () => output)

    await expect(service.start(0)).resolves.toEqual({ activeBit: 0 })
    expect(output.receivedSamples).toHaveLength(120000)
    await expect(service.stop()).resolves.toEqual({ activeBit: null })
    expect(output.stopped).toBe(true)
    expect(output.disposed).toBe(true)
  })
})
